### ISSUE TITLE
Support V2 XcmExecutor

### ISSUE THREAD

**Issue by gregdhill** [zenlinkpro/Zenlink-DEX-Module#36]
The trait bound [here](https://github.com/zenlinkpro/Zenlink-DEX-Module/blob/29cc1963ce393df2968b695c0f80b1216f97c8f4/zenlink-protocol/src/lib.rs#L92) should use `xcm::v2::ExecuteXcm` for the latest `XcmExecutor`.

**Comment by byterui** [comment]
Because ZenlinkProtocol Pallet is currently not suitable for cross-chain asset transfer, it may lead to asset fragmentation on parachain. We plan to do cross-chain transactions based on the cross-chain asset transfer function of the chain itself. Therefore, it is better to turn off the cross-chain asset transfer function for now and set XcmExecutor to () in the Runtime configuration.

**Comment by byterui** [comment]
https://github.com/zenlinkpro/bifrost/blob/develop/runtime/bifrost-kusama/src/lib.rs#L1857．This is a configuration in a production environment. It runs stably on bifrost kusama.
